const VALUES = {
  API_URI: 'http://192.168.25.4:4000/expo-notifications/api/v1',
  ANDROID_NOTIFICATIONS_CHANNEL: '@EXPO_NOTIFICATIONS-APP',
  ASYNC_STORAGE_KEY: '@EXPO_NOTIFICATIONS-APP',
};

export default {
  VALUES,
};
